# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-05 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default=list, max_length=32),
        ),
    ]
